# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190428_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='\uc11c\uc6b8', max_length=20),
        ),
    ]
