# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
